name: Build and Deploy to Netlify

#on:
#  pull_request:
#    branches: 
#      - main
#    types: 
#      - closed
# For testing
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build 
      
      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true    
