name: Build and Deploy to Netlify

on:
 pull_request:
   branches: 
     - main
   types: 
     - closed

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:      
      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true    
